name: CI
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: 3.11
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run checks
        run: python manage.py check
